### ISSUE TITLE
which xr version you test?

### ISSUE THREAD

**Issue by xizha2** [nleiva/xr-gnmi#1]
hi,

May i ask which xr version you are using for gnmi testing? I am using xrv9k-6.5.1.

In cli-get.md example, execute the "Two paths on a request" example, but got the error response as below:

target returned RPC error for Get("prefix:<origin:\"openconfig-interfaces\" > path:<elem:<name:\"interfaces\" > elem:<name:\"interface\" key:<key:\"name\" value:\"GigabitEthernet0/0/0/1\" > > > type:CONFIG encoding:JSON_IETF "): rpc error: code = Internal desc = gNMI get-request: rpc error: code = Internal desc = lexical error: invalid char in json text.
                                        {"openconfig-interfaces:interf
                     (right here) ------^

**Comment by nleiva** [comment]
Could you try adding extra quotes to the interface values like this: `"\"Loopback60\""` (with escape).

**Comment by xizha2** [comment]
Thanks! It works!

**Comment by svautour** [comment]
This solved my problem as well. Thanks!
